#!/bin/sh

# Ensure ruby is installed
if ! command -v ruby >/dev/null 2>/dev/null
then
	echo >&2 'ERROR:

The Knight tester requires ruby to be installed. Please install ruby and try
again! (There is quite a few ways to get Ruby; one good way is https://rvm.io.)

If you do have ruby installed, please check your $PATH and try again.'
	exit 3
fi

# Ensure that a ruby of the right version is installed
ruby_version=$(ruby --version)
case $ruby_version in
	ruby\ 3*) : ;; # We support 3.0.0 and up.
	*) echo >&2 "ERROR:

The ruby version you're using is too old. Please upgrade to 3.0.0.
Version: $ruby_version"
	exit 3
esac

# Get the directory that contains the script. We need this hack in case the
# folder ends in a `\n` for some bizarre reason.
script_dir=$(dirname -- "$0" && printf x) || {
	printf >&2 'there was a problem finding the directory the script is in'
	exit 3
}

script_dir=${script_dir%?x}
exec ruby "$script_dir/tests/entrypoint.rb" "$@"
