#!/bin/sh

echo "NOTE: THIS PROBABLY DOESN'T WORK"
if [ $# = 0 ]; then
	echo "usage: $0 [-nocapture] [executable]" >/dev/stderr
	exit 1
fi

if [ '-nocapture' = "$1" ]; then
	nocapture=1
	shift
fi

: "${KNIGHT_HOME:="$(dirname "$0")"}"

runit () {
	time "$@" -f "$KNIGHT_HOME/examples/knight.kn" <<EOS
$KNIGHT_HOME/examples/knight.kn
$KNIGHT_HOME/examples/fizzbuzz.kn
EOS
}

for _ in $(seq 1 5); do
	if [ -z "$nocapture" ]; then
		runit "$@" >/dev/null
	else
		runit "$@"
	fi || exit 1
done
